### ISSUE TITLE
HI

### ISSUE THREAD

**Issue by wwq0327** [manateelazycat/deepin-software-center#2]
hi,

我现在用的是Ubuntu，软件中心用得也不多，但看到deepin这个软件中心，觉得真的做得不错。但我仍暂时没有打算切换到deepin上去。我试过把代码clone下来，在Ubuntu上跑了下，还勉强能用，UI做得很赞，如果这个工具能放到Ubuntu上来，我觉得真是很不错，不防考虑下。

**Comment by manateelazycat** [comment]
你好， 谢谢你的支持！

我正在开发软件中心 2.0， 其实软件中心不兼容 Ubuntu 的原因不是因为代码的问题， 而是很多首页推荐软件在 Ubuntu 的源没有，
导致软件中心不能正常启动。

我打算在2.0里开放首页推荐接口， 这样 Ubuntu 或其他 Debian 社区的人， 可以更改首页推荐列表以兼容各个发行版。

在 2011年9月20日 下午4:05，wwq0327 <
reply@reply.github.com>
写道：

**Comment by manateelazycat** [comment]
你好， 谢谢你的支持！

我正在开发软件中心 2.0， 其实软件中心不兼容 Ubuntu 的原因不是因为代码的问题， 而是很多首页推荐软件在 Ubuntu 的源没有， 导致软件中心不能正常启动。

我打算在2.0里开放首页推荐接口， 这样 Ubuntu 或其他 Debian 社区的人， 可以更改首页推荐列表以兼容各个发行版。

**Comment by wwq0327** [comment]
原来这样呀，我当是是胡乱修改了下，然后运行起来了。可以考虑弄个设置功能，用户能控制源，这样可能比较好。

首页的推荐也可以考虑采用现下流行的Web2.0方式，根据用户的评级去自动推荐，我只是跑了一次，具体的细节我也不记得，但我心里话，这个做得真不错。Debian系列所有的平台上一定很酷。

看你仅凭一人之力，就搞出这么个很棒的软件出来，真是羡慕呀。我也在学习Python，不过还在努力。

**Comment by manateelazycat** [comment]
软件中心2.0的网络功能已经开发出来， 可以根据服务器的更新自动推荐好的软件。
在2.0， 我会采用公开接口的方式， 这样各个社区的维护人可以 fork 一份并维护自己的服务器， 这样对各个社区的终端用户更好一点。

呵呵， 大家一起学习嘛， 欢迎提交补丁和建议！ :)

在 2011年9月21日 下午8:29，wwq0327 <
reply@reply.github.com>
写道：
